### ISSUE TITLE
Adapter bleibt rot

### ISSUE THREAD

**Issue by Negalein** [Jey-Cee/ioBroker.net-tools#1]
```
net-tools.0	2020-09-26 17:28:29.182	info	(780) Terminated (NO_ERROR): Without reason
net-tools.0	2020-09-26 17:28:29.181	info	(780) terminating
net-tools.0	2020-09-26 17:28:28.672	error	at processTicksAndRejections (internal/process/task_queues.js:97:5)
net-tools.0	2020-09-26 17:28:28.672	error	at portScan (/opt/iobroker/node_modules/iobroker.net-tools/main.js:132:15)
net-tools.0	2020-09-26 17:28:28.672	error	(780) TypeError: Cannot read property 'val' of null
net-tools.0	2020-09-26 17:28:28.671	error	(780) unhandled promise rejection: Cannot read property 'val' of null
net-tools.0	2020-09-26 17:28:28.573	info	(780) starting. Version 0.1.0 in /opt/iobroker/node_modules/iobroker.net-tools, node: v12.18.3, js-controller: 3.1.6
```

Geräte lassen sich auch keine anlegen.

**Comment by Negalein** [comment]
läuft wieder
