### ISSUE TITLE
[Bug]: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by Jey-Cee** [Jey-Cee/ioBroker.net-tools#11]
### What happened?

Adapter crash.

### Adapter Version

0.1.7

### JS-Controller Version

3.3.18

### Node JS Version

12

### NPM Version

6.14.14

### Operating System

Debian

### Relevant log output

```shell
host.Debian
    2021-10-22 18:02:01.705    warn    Do not restart adapter system.adapter.net-tools.0 because restart loop detected
host.Debian
    2021-10-22 18:02:01.704    error    instance system.adapter.net-tools.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
net-tools.0
    2021-10-22 18:02:01.141    warn    Terminated (UNCAUGHT_EXCEPTION): Without reason
net-tools.0
    2021-10-22 18:02:00.633    error    Cannot read property 'toLowerCase' of undefined
net-tools.0
    2021-10-22 18:02:00.632    error    TypeError: Cannot read property 'toLowerCase' of undefined at addDevice (/opt/iobroker/node_modules/iobroker.net-tools/main.js:283:19) at async processMessage (/opt/iobroker/node_modules/iobroker.net-tools/main.js:93:13)
net-tools.0
    2021-10-22 18:02:00.630    error    unhandled promise rejection: Cannot read property 'toLowerCase' of undefined
net-tools.0
    2021-10-22 18:02:00.629    error    Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
host.Debian
    2021-10-22 18:00:43.925    error    instance system.adapter.net-tools.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
net-tools.0
    2021-10-22 18:00:39.290    warn    Terminated (UNCAUGHT_EXCEPTION): Without reason
net-tools.0
    2021-10-22 18:00:38.442    error    Cannot read property 'toLowerCase' of undefined
net-tools.0
    2021-10-22 18:00:38.441    error    TypeError: Cannot read property 'toLowerCase' of undefined at addDevice (/opt/iobroker/node_modules/iobroker.net-tools/main.js:283:19) at async processMessage (/opt/iobroker/node_modules/iobroker.net-tools/main.js:93:13)
net-tools.0
    2021-10-22 18:00:38.440    error    unhandled promise rejection: Cannot read property 'toLowerCase' of undefined
net-tools.0
```

**Comment by rookie50** [comment]
As workarround: enter the mac address. When I leave it empty i will get the same error.

**Comment by Jey-Cee** [comment]
@rookie50 on which OS does your ioBroker installation run?

**Comment by Jey-Cee** [comment]
Please test the new version, 0.2.0.
